apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceName }}
spec:
  serviceName: {{ .Values.serviceName | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Values.serviceName }}
        imagePullPolicy: Always
        env:
          - name: PASSWORD
            value: {{ .Values.idePassword | quote }}
        ports:
        - containerPort: 8080
          name: ide-worker
        volumeMounts:
          - name: ide-data
            mountPath: /data
          - name: ide-projects
            mountPath: /home/coder/project/
      volumes:
        - name: ide-data
          persistentVolumeClaim:
            claimName: ide-data
        - name: ide-projects
          persistentVolumeClaim:
            claimName: ide-projects
