apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    type: "website"
    url: {{ .Values.serviceURL | quote }}
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: {{ .Values.serviceURL | quote }}
---